version: '2'

services:
  rabbitmq:
    image: rabbitmq:3.6
    ports:
      - "5672:5672"
  zookeeper:
    image: jplock/zookeeper
  marathon:
    image: mesosphere/marathon:v1.4.0
    command:
      --master local --zk zk://zookeeper:2181/marathon
    links:
      - zookeeper
    ports:
      - "8080:8080"
    environment:
      - MESOS_CLUSTER=local
      - MESOS_HOSTNAME=mesos-master.docker
      - MESOS_LOG_DIR=/var/log
      - MESOS_QUORUM=1
      - MESOS_WORK_DIR=/var/lib/mesos
      - MESOS_ROLES=public
      - MESOS_ZK=zk://zookeeper:2181/mesos